data: './captions.txt'
data_ner: './captions_ner.txt'
ngram_number: 20 # top 20 of most ngram

model: "مدل و نوع"
price: "قیمت"
style: "استایل"
size: "سایز"
season: "فصل"
originality: "اصالت"
quality: "کیفیت"
texture: "جنس"
sex: "جنسیت"
brand: "برند"
location: "مکان"
weight: "وزن"
color: "رنگ"
product: "محصول"